version: '3.9'

services:
  update:
    image: awsterraformcontainer
    network_mode: host
    working_dir: /app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    entrypoint: ["sh", "-c"]
    command: ["sh awsRun.sh"]
